snapshot:
  path: "./snapshots/"
  mute: false
  codeAdmissibleChars: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
  uniqueCodeSize: 8

network:
  PingPongTimeout: 5000
  directConnectionProbability: 0.7
  ackTimeout: 5000

logger:
  showLogInSOut: true


# all the parameters and the file itself are optional