snapshot:
  path: "./snapshots/"
  codeAdmissibleChars: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
  uniqueCodeSize: 8

network:
  PingPongTimeout: 5000
  directConnectionProbability: 1
  ackTimeout: 5000

logger:
  mute: false
  showLogInSOut: false


# all the parameters and the file itself are optional